Repaired yodl2whatever
git-svn-id: https://stealth.svn.sourceforge.net/svnroot/yodl/trunk@164 7de777c3-3b1c-0410-83c5-80958bd9f4b1

diff --git a/yodl/scripts/yodl2whatever.in b/yodl/scripts/yodl2whatever.in
--- a/yodl/scripts/yodl2whatever.in
+++ b/yodl/scripts/yodl2whatever.in
@@ -70,7 +70,7 @@ run()
     if [ "$verbose" = "yes" ]; then
     echo running "$*"
     fi
-    $* || error "$1 indicates failure!"
+    eval $* || error "$1 indicates failure!"
 }
 
 ############################################################# Start of script.
